### ISSUE TITLE
Could not initialize class sun.awt.X11FontManager

### ISSUE THREAD

**Issue by flaviolenz** [knowm/XChart#307]
Suddenly (app and server is not updated for over 3 weeks), I started getting this error in two (out of 3) Ubuntu 18.04 servers:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.desktop/java.awt.Font.getFont2D(Font.java:497)
        at java.desktop/java.awt.Font.defaultLineMetrics(Font.java:2362)
        at java.desktop/java.awt.Font.getLineMetrics(Font.java:2469)
        at java.desktop/java.awt.font.TextLayout.fastInit(TextLayout.java:597)
        at java.desktop/java.awt.font.TextLayout.<init>(TextLayout.java:392)
        at org.knowm.xchart.internal.chartpart.ChartTitle.getBoundsHint(ChartTitle.java:109)
        at org.knowm.xchart.internal.chartpart.ChartTitle.getBounds(ChartTitle.java:130)
        at org.knowm.xchart.internal.chartpart.Axis.preparePaint(Axis.java:106)
        at org.knowm.xchart.internal.chartpart.AxisPair.paint(AxisPair.java:91)
        at org.knowm.xchart.XYChart.paint(XYChart.java:415)
        at org.knowm.xchart.BitmapEncoder.getBufferedImage(BitmapEncoder.java:285)
        at org.knowm.xchart.BitmapEncoder.getBitmapBytes(BitmapEncoder.java:265)
        at contahub.cmds.ChartCmd.getImgGraficoVendasHoras(ChartCmd.java:439)
-----
code is something like this:
CategoryChart chart =new CategoryChartBuilder() ...
...
byte[] bytes = BitmapEncoder.getBitmapBytes(chart, BitmapFormat.PNG);

------
This is a webapp and not an AWT java application. Charts are always created and converted to PNG images.
The strange thing is that one of my servers (installed exactly the same as others) doesn get this error.
Yesterday, it was working fine. 
I didnt change anything in the environment. 
Maybe OpenJDK was automatically updated and generated this issue (searching the web, the error seems to be related to OpenJDK)

This is the version on the two servers with errors:
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

This is the one with no problem:
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

Any idea?

**Comment by flaviolenz** [comment]
Installed OpenJDK 8 (without purging OpenJDK 11), restarted Tomcat, and it is working now.
(dont know if i had just restarted tomcat it would be ok)

**Comment by timmolter** [comment]
you could try setting the headless mode. 

https://stackoverflow.com/questions/21131855/could-not-initialize-class-sun-awt-x11graphicsenvironment-on-solaris

Tomcat has a config file somewhere for that.

**Comment by Mr14huashao** [comment]
In Tomcat/bin/catalina.sh, add `-Djava.awt.headless=true`

as follows:
JAVA_OPTS="$JAVA_OPTS -Djava.awt.headless=true"
![awt headless](https://user-images.githubusercontent.com/57353473/76721668-bb588380-677b-11ea-822b-3f05c073326a.png)

**Comment by Mr14huashao** [comment]
@timmolter 
According to the link you provided, this issue should be resolved.
This issue can be closed.
