### ISSUE TITLE
XChartStyleDemo running error

### ISSUE THREAD

**Issue by Mr14huashao** [knowm/XChart#378]
Exception information:
```java
Skipping property (no read method): chart.chartXFromCoordinate null
Skipping property (no read method): chart.chartYFromCoordinate null
Warning no editor found for property 'chart.infoContent' with class class java.util.ArrayList
Skipping property (no write method): chart.plotParts class java.util.ArrayList
Skipping property (no read method): chart.XAxisLabelOverrideMap interface java.util.Map
Skipping property (no read method): chart.YAxisLabelOverrideMap interface java.util.Map
Skipping property (no write method): chart.YAxisLeftWidth double
Skipping property (no read method): styler.YAxisGroupPosistion null
Skipping property (no write method): styler.YAxisMax class java.lang.Double
Skipping property (no write method): styler.YAxisMin class java.lang.Double
Error reading chart.YAxisGroupPosition[0]
java.lang.IllegalArgumentException: Argument is not an array
	at java.lang.reflect.Array.get(Native Method)
	at org.knowm.xchart.demo.ChartStylePanel$EditableProperty.getValue(ChartStylePanel.java:301)
	at org.knowm.xchart.demo.ChartStylePanel$EditableProperty.initEditor(ChartStylePanel.java:220)
	at org.knowm.xchart.demo.ChartStylePanel$EditableProperty.<init>(ChartStylePanel.java:214)
	at org.knowm.xchart.demo.ChartStylePanel.getProperties(ChartStylePanel.java:631)
	at org.knowm.xchart.demo.ChartStylePanel$EditorTableModel.changeChart(ChartStylePanel.java:425)
	at org.knowm.xchart.demo.ChartStylePanel$EditorTableModel.<init>(ChartStylePanel.java:419)
	at org.knowm.xchart.demo.ChartStylePanel$EditorTable.<init>(ChartStylePanel.java:489)
	at org.knowm.xchart.demo.ChartStylePanel.<init>(ChartStylePanel.java:531)
	at org.knowm.xchart.demo.XChartStyleDemo.<init>(XChartStyleDemo.java:18)
```
@hakantkn 
ChartStylePanel.getProperties 629 line 
```java
Method readMethod = stylerMethodMap.get("getyaxisgroupposition");
styleEditor =
	new EditableProperty(
		csp,
		"chart.YAxisGroupPosition[" + i + "]",
		chart.getStyler(),
		readMethod,
		stylerMethodMap.get("setyaxisgroupposition"),
		i);
list.add(styleEditor);
``
chart has no setyaxisgroupposition method，The above code is deleted, and no error is reported.

ChartStylePanel class has not been updated for a long time.

**Comment by timmolter** [comment]
If you have a suggestion for a fix please feel free to submit a PR. Thanks!
