### ISSUE TITLE
When chart.addSeries ("a", null), NullPointerException will be thrown here

### ISSUE THREAD

**Issue by Mr14huashao** [knowm/XChart#379]
In pie chart, java.lang.NullPointerException will be thrown when chart.addSeries ("a", null).
@timmolter 
Are you considering processing in the addSeries function and throwing an IllegalArgumentException? Or when null, skip it？

```java
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.knowm.xchart.internal.chartpart.PlotContent_Pie.doPaint(PlotContent_Pie.java:118)
	at org.knowm.xchart.internal.chartpart.PlotContent_.paint(PlotContent_.java:48)
	at org.knowm.xchart.internal.chartpart.Plot_.paint(Plot_.java:37)
	at org.knowm.xchart.internal.chartpart.Plot_Circular.paint(Plot_Circular.java:55)
	at org.knowm.xchart.PieChart.paint(PieChart.java:128)
	at org.knowm.xchart.XChartPanel.paintComponent(XChartPanel.java:110)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.awt.Container.paint(Unknown Source)
	at java.awt.Window.paint(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by timmolter** [comment]
I guess that's a more general question, not just relevant to the `addSeries` method, right? I don;'t think it's really necessary because the NPE indicates to the end user what the issue is. What's the value of adding `null` checks? It's a performance hit.

**Comment by Mr14huashao** [comment]
> I guess that's a more general question, not just relevant to the `addSeries` method, right? I don;'t think it's really necessary because the NPE indicates to the end user what the issue is. What's the value of adding `null` checks? It's a performance hit.

It can be seen from other charts that when xy charts, bar charts, etc. encounter `null`, they will skip it. I think when the pie chart encounters `null`, it should be skipped (because the `null` parameter is supported).
@timmolter and what do you think?

**Comment by timmolter** [comment]
ok, then skip it like it is done elsewhere
