### ISSUE TITLE
NPE at at org.knowm.xchart.internal.chartpart.PlotContent_XY.doPaint(PlotContent_XY.java:60)

### ISSUE THREAD

**Issue by crowlogic** [knowm/XChart#414]
java.lang.NullPointerException
	at org.knowm.xchart.internal.chartpart.PlotContent_XY.doPaint(PlotContent_XY.java:60)
	at org.knowm.xchart.internal.chartpart.PlotContent_.paint(PlotContent_.java:51)
	at org.knowm.xchart.internal.chartpart.Plot_.paint(Plot_.java:37)
	at org.knowm.xchart.internal.chartpart.Plot_AxesChart.paint(Plot_AxesChart.java:35)
	at org.knowm.xchart.XYChart.paint(XYChart.java:418)
	at org.knowm.xchart.XChartPanel.paintComponent(XChartPanel.java:113)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by timmolter** [comment]
Can you post code that produces the error? Otherwise there's no way for me to debug and fix the issue...

**Comment by crowlogic** [comment]
I cannot unfortunately.. but I think the fix is as easy as checking for null yAxis

      Axis yAxis = chart.getYAxis(series.getYAxisGroup());
      double yMin = yAxis.getMin();

in PlotContent_XY.java

if ( yAxis == nuil )
   continue;

just like the isEnabled check before it

**Comment by crowlogic** [comment]
It happens in a multithreaded situation where the chart is being constructed, a refresh happens. but the chart isnt all the way complete

**Comment by Mr14huashao** [comment]
@crowlogic @timmolter 
This situation occurs when multiple threads are drawing the same Chart. When drawing the axisPair, the `prepareForPaint()` method will clear the `yAxisMap`.
```java
private void prepareForPaint() {

    yAxisMap.clear();
    ...
}
```
When `yAxis == null`  skip, the Chart drawing will be inaccurate.

You can add synchronization when multiple threads draw the same Chart.

**Comment by timmolter** [comment]
We didn't make this library with multiple threads updating the chart in mind so it's not surprising that this issue is occurring. I don't want to add null checks all over the codebase and chase these errors until the end of time. Maybe someone can post some threadsafe code as @Mr14huashao mentioned and we can direct people towards that. We could even post it in the FAQ.
