### ISSUE TITLE
Impossible to save jpg images

### ISSUE THREAD

**Issue by Wouter-Bosma** [knowm/XChart#494]
After resolving issue 488 adding alpha channels, it is no longer possible to save jpg files. This (implementation of this) format doesn't support alpha channels.

**Comment by Mr14huashao** [comment]
Execute `BitmapEncoder.saveBitmap(Chart chart, String fileName, BitmapFormat bitmapFormat)` throws an exception

When bitmapFormat = `BitmapEncoder.BitmapFormat.BMP`, the saved picture content is empty. 

When bitmapFormat = `BitmapEncoder.BitmapFormat.JPG`, the saved picture content is empty and an exception is thrown
```java
javax.imageio.IIOException: Invalid argument to native writeImage
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1067)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:363)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1622)
	at javax.imageio.ImageIO.write(ImageIO.java:1588)
	at org.knowm.xchart.BitmapEncoder.saveBitmap(BitmapEncoder.java:86)
	at org.knowm.xchart.BitmapEncoder.saveBitmap(BitmapEncoder.java:69)
	at org.knowm.xchart.demo.charts.pie.PieChartTest.getChart(PieChartTest.java:81)
	at org.knowm.xchart.demo.charts.pie.PieChartTest.getChart(PieChartTest.java:1)
	at org.knowm.xchart.demo.charts.pie.PieChartTest.main(PieChartTest.java:36)
```
