### ISSUE TITLE
Getting a NoClassDefFoundError after a while of running the application.

### ISSUE THREAD

**Issue by dieterblancke** [knowm/XChart#513]
After a while, I get this exception, oddly enough, this does not happen in the first few hours of running my application, suddenly this error starts happening when a Chart is being generated and converted to a byte array.

This is running on a Linux VPS (Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-43-generic x86_64))

The code for getting the byte array from my chart:
```
        try
        {
            return BitmapEncoder.getBitmapBytes( chart, BitmapEncoder.BitmapFormat.PNG );
        }
        catch ( IOException e )
        {
            e.printStackTrace();
            return null;
        }
```

The error:
```
Exception in thread "pool-2-thread-49" java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at org.knowm.xchart.BitmapEncoder.getBufferedImage(BitmapEncoder.java:279)
        at org.knowm.xchart.BitmapEncoder.getBitmapBytes(BitmapEncoder.java:263)
        at com.dbsoftwares.wynnstats.discord.chart.PlayerOnlineTimeChart.getOnlineTimeChart(PlayerOnlineTimeChart.java:63)
        at com.dbsoftwares.wynnstats.web.requesthandlers.playeronlinetime.PlayerOnlineTimeChartPage.handle(PlayerOnlineTimeChartPage.java:27)
        at express.filter.FilterImpl.handle(FilterImpl.java:100)
        at express.filter.FilterLayer.filter(FilterLayer.java:41)
        at express.filter.FilterLayerHandler.handle(FilterLayerHandler.java:36)
        at express.Express.lambda$listen$3(Express.java:372)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by timmolter** [comment]
Very odd. Could be related to these:

https://confluence.atlassian.com/bitbucketserverkb/linux-installer-fails-with-java-lang-noclassdeffounderror-could-not-initialize-class-sun-awt-x11graphicsenvironment-error-938843519.html

https://github.com/rycus86/docker-intellij-idea/issues/11

Maybe the `Make sure you are not running out of disk space` issue??
