### ISSUE TITLE
java.lang.NumberFormatException: Character N is neither a decimal digit number after upgrading to 3.6.6

### ISSUE THREAD

**Issue by Aloren** [knowm/XChart#536]
After upgrading from 3.6.5 to 3.6.6 version the following test starts to fail:
```
    @Test
    void test() throws Exception {
        XYChart chart = new XYChart(800, 600);

        List<? extends Number> values = List.of(NaN, NaN, NaN);
        List<? extends Number> times = List.of(1L, 2L, 3L);
        XYSeries series = chart.addSeries("Series", times, values);
        series.setMarker(SeriesMarkers.NONE);

        byte[] bytes = BitmapEncoder.getBitmapBytes(chart, BitmapEncoder.BitmapFormat.PNG);
    }
```

Here is the stacktrace:
```
java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:518)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:401)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834)
	at java.base/java.math.BigDecimal.valueOf(BigDecimal.java:1304)
	at org.knowm.xchart.internal.chartpart.AxisTickCalculator_.calculate(AxisTickCalculator_.java:295)
	at org.knowm.xchart.internal.chartpart.AxisTickCalculator_Number.<init>(AxisTickCalculator_Number.java:47)
	at org.knowm.xchart.internal.chartpart.Axis.getAxisTickCalculator(Axis.java:572)
	at org.knowm.xchart.internal.chartpart.Axis.getYAxisWidthHint(Axis.java:349)
	at org.knowm.xchart.internal.chartpart.Axis.preparePaint(Axis.java:159)
	at org.knowm.xchart.internal.chartpart.AxisPair.paint(AxisPair.java:124)
	at org.knowm.xchart.XYChart.paint(XYChart.java:417)
	at org.knowm.xchart.BitmapEncoder.getBufferedImage(BitmapEncoder.java:281)
	at org.knowm.xchart.BitmapEncoder.getBitmapBytes(BitmapEncoder.java:264)
	at yyy.MetricChartCreatorTest.test(MetricChartCreatorTest.java:69)
```

**Comment by Aloren** [comment]
Looks like the issue was introduced in the following change: https://github.com/knowm/XChart/commit/d73f083ef46b54514df0a4b04c9e767b1304d520

**Comment by timmolter** [comment]
@MrcJkb Would you be willing to take a look at this??

**Comment by MrcJkb** [comment]
Yes

**Comment by Aloren** [comment]
thank you guys!
