### ISSUE TITLE
Error passing null values in series

### ISSUE THREAD

**Issue by tberne** [knowm/XChart#543]
First of all, thanks for the great tool!

When adding a `null` value in the series values (like in [this example](https://gist.github.com/tberne/f89e41b4a2ed4b9e72c32cce540cadb4)), the following exception is thrown:
```
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:518)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:401)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834)
	at java.base/java.math.BigDecimal.valueOf(BigDecimal.java:1304)
	at org.knowm.xchart.internal.chartpart.AxisTickCalculator_.calculate(AxisTickCalculator_.java:295)
	at org.knowm.xchart.internal.chartpart.AxisTickCalculator_Number.<init>(AxisTickCalculator_Number.java:47)
	at org.knowm.xchart.internal.chartpart.Axis.getAxisTickCalculator(Axis.java:572)
	at org.knowm.xchart.internal.chartpart.Axis.getYAxisWidthHint(Axis.java:349)
	at org.knowm.xchart.internal.chartpart.Axis.preparePaint(Axis.java:159)
	at org.knowm.xchart.internal.chartpart.AxisPair.paint(AxisPair.java:124)
	at org.knowm.xchart.XYChart.paint(XYChart.java:417)
	at org.knowm.xchart.XChartPanel.paintComponent(XChartPanel.java:132)
	...
```

I'm using XY chart.

It is imperative that I can add `null` values because the chart I'm plotting is a chart of average values. And an average of 0 is different from the absence of values.

**Comment by timmolter** [comment]
Hi, use 3.6.5 for now. There was a recent bug introduced. New version coming soon.

**Comment by timmolter** [comment]
FYI, 3.7.0 released.

**Comment by tberne** [comment]
@timmolter , thanks for your time!! And, once again, thanks for the great tool!
