### ISSUE TITLE
How to create an "empty" chart

### ISSUE THREAD

**Issue by tberne** [knowm/XChart#544]
Hi.
I'm trying to fix a situation where I have no data to display in chart. In @chartjs I can do that. The chart is printed like so: 
![image](https://user-images.githubusercontent.com/10933706/103028263-2bc7d880-4536-11eb-9c64-71d065daebe2.png)

Either when I try to create the chart without any series or when I add a series with zero-length arrays (for X and Y axis), I get an Exception.

With a series with empty values:
```
Exception in thread "main" java.lang.IllegalArgumentException: Y-Axis data cannot be empty!!!
	at org.knowm.xchart.CategoryChart.sanityCheck(CategoryChart.java:280)
	at org.knowm.xchart.CategoryChart.addSeries(CategoryChart.java:167)
	at org.knowm.xchart.CategoryChart.addSeries(CategoryChart.java:148)
	at LineChart04.getChart(LineChart04.java:40)
	at LineChart04.main(LineChart04.java:18)
```

With no series at all:

```
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746)
	at org.knowm.xchart.internal.chartpart.Axis.getAxisTickCalculator(Axis.java:480)
	at org.knowm.xchart.internal.chartpart.Axis.getXAxisHeightHint(Axis.java:289)
	at org.knowm.xchart.internal.chartpart.Axis.preparePaint(Axis.java:153)
	at org.knowm.xchart.internal.chartpart.AxisPair.paint(AxisPair.java:124)
	at org.knowm.xchart.CategoryChart.paint(CategoryChart.java:308)
	at org.knowm.xchart.XChartPanel.paintComponent(XChartPanel.java:132)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5262)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3940)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I'm using the version `3.6.6`.

**Comment by tberne** [comment]
[Here's the example](https://gist.github.com/tberne/be04ba3fcfa0beb68cdd9e5fd8c74a82) that I've used to test it.

**Comment by timmolter** [comment]
You can use the following on a series:

```java
series.setEnabled(false);
```

as a workaround. I never thought there'd be a usecase where someone would need to display an empty chart. I could perhaps add it if it's justified.

**Comment by timmolter** [comment]
```java
 public CategoryChart getChart() {

    // Create Chart
    CategoryChart chart =
        new CategoryChartBuilder()
            .width(800)
            .height(600)
            .title("LineChart04")
            .xAxisTitle("X")
            .yAxisTitle("Y")
            .build();

    // Customize Chart
    chart.getStyler().setLegendVisible(false);
    CategorySeries series =
        chart.addSeries("A", new double[] {0.0, 1.0, 3.0}, new double[] {0.0, 10.0, 20.0});
    series.setEnabled(false);
    return chart;
  }
```

<img width="800" alt="Screen Shot 2020-12-25 at 4 45 05 PM" src="https://user-images.githubusercontent.com/738972/103138214-93b22680-46d0-11eb-90c0-c745f7ba30cc.png">

**Comment by tberne** [comment]
> You can use the following on a series:
> 
> ```java
> series.setEnabled(false);
> ```
> 
> as a workaround. I never thought there'd be a usecase where someone would need to display an empty chart. I could perhaps add it if it's justified.

Thanks! I'll try that!

**Comment by tberne** [comment]
@timmolter, It worked as expected! Thanks for your help!
