### ISSUE TITLE
Can't see the file explorer

### ISSUE THREAD

**Issue by IbrahimElsayed26498** [knowm/XChart#594]
I'm trying to run "XChartDemo" 
![image](https://user-images.githubusercontent.com/43645654/117586447-8d20ca80-b118-11eb-85d3-31a31dc7eaf2.png)
when using the file explorer, it doesn't work and gives me an exception.

**Comment by IbrahimElsayed26498** [comment]
"C:\Program Files\Java\jdk-16.0.1\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\idea_rt.jar=64269:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\bin" -Dfile.encoding=UTF-8 -classpath "E:\FEE\2nd Term\XChart\xchart-demo\target\classes;E:\FEE\2nd Term\XChart\xchart\target\classes;C:\Users\MBR\.m2\repository\de\erichseifert\vectorgraphics2d\VectorGraphics2D\0.13\VectorGraphics2D-0.13.jar;C:\Users\MBR\.m2\repository\de\rototor\pdfbox\graphics2d\0.31\graphics2d-0.31.jar;C:\Users\MBR\.m2\repository\org\apache\pdfbox\pdfbox\2.0.22\pdfbox-2.0.22.jar;C:\Users\MBR\.m2\repository\org\apache\pdfbox\fontbox\2.0.22\fontbox-2.0.22.jar;C:\Users\MBR\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\MBR\.m2\repository\com\madgag\animated-gif-lib\1.4\animated-gif-lib-1.4.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-swing\11.0.2\javafx-swing-11.0.2.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-swing\11.0.2\javafx-swing-11.0.2-win.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-graphics\11.0.2\javafx-graphics-11.0.2.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-graphics\11.0.2\javafx-graphics-11.0.2-win.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-base\11.0.2\javafx-base-11.0.2.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-base\11.0.2\javafx-base-11.0.2-win.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-controls\11.0.2\javafx-controls-11.0.2.jar;C:\Users\MBR\.m2\repository\org\openjfx\javafx-controls\11.0.2\javafx-controls-11.0.2-win.jar" org.knowm.xchart.demo.XChartDemoException in thread "AWT-EventQueue-0" java.lang.ClassCastException: class java.lang.String cannot be cast to class org.knowm.xchart.demo.ChartInfo (java.lang.String is in module java.base of loader 'bootstrap'; org.knowm.xchart.demo.ChartInfo is in unnamed module of loader 'app')at org.knowm.xchart.demo.XChartDemo.valueChanged(XChartDemo.java:87)at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3466)at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1656)at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2764)at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4099)at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:4038)at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)at java.desktop/java.awt.Component.processEvent(Component.java:6382)at java.desktop/java.awt.Container.processEvent(Container.java:2264)at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4560)at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Mohamed-Hany97** [comment]
I have the same error. Do you solve it ?

**Comment by IbrahimElsayed26498** [comment]
Unfortunately no.
