### ISSUE TITLE
Java 17 issue

### ISSUE THREAD

**Issue by stovan12** [knowm/XChart#648]
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262) ~[?:?]
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224) ~[?:?]
	at sun.awt.FontConfiguration.init(FontConfiguration.java:106) ~[?:?]
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706) ~[?:?]
	at sun.font.SunFontManager$2.run(SunFontManager.java:358) ~[?:?]
	at sun.font.SunFontManager$2.run(SunFontManager.java:315) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at sun.font.SunFontManager.<init>(SunFontManager.java:315) ~[?:?]
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[?:?]
	at sun.awt.X11FontManager.<init>(X11FontManager.java:56) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:85) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75) ~[?:?]
	at java.awt.Font.getFont2D(Font.java:526) ~[?:?]
	at java.awt.Font.defaultLineMetrics(Font.java:2398) ~[?:?]
	at java.awt.Font.getLineMetrics(Font.java:2505) ~[?:?]
	at java.awt.font.TextLayout.fastInit(TextLayout.java:597) ~[?:?]
	at java.awt.font.TextLayout.<init>(TextLayout.java:392) ~[?:?]
	at org.knowm.xchart.internal.chartpart.ChartTitle.getBoundsHint(ChartTitle.java:109) ~[hub-1.1.jar:?]
	at org.knowm.xchart.internal.chartpart.ChartTitle.getBounds(ChartTitle.java:130) ~[hub-1.1.jar:?]
	at org.knowm.xchart.internal.chartpart.Axis.preparePaint(Axis.java:128) ~[hub-1.1.jar:?]
	at org.knowm.xchart.internal.chartpart.AxisPair.paint(AxisPair.java:121) ~[hub-1.1.jar:?]
	at org.knowm.xchart.XYChart.paint(XYChart.java:416) ~[hub-1.1.jar:?]
	at org.knowm.xchart.BitmapEncoder.getBufferedImage(BitmapEncoder.java:281) ~[hub-1.1.jar:?]
	at org.knowm.xchart.BitmapEncoder.saveBitmap(BitmapEncoder.java:85) ~[hub-1.1.jar:?]
	at org.knowm.xchart.BitmapEncoder.saveBitmap(BitmapEncoder.java:69) ~[hub-1.1.jar:?]
	
Worked fine in java 16, updated to java 17 and its broken

version:
openjdk 17.0.1 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.1.12.1 (build 17.0.1+12-LTS, mixed mode, sharing)

Using:
 3.8.1

**Comment by futurechan** [comment]
i'm also having problems with the library and jdk 17.

**Comment by jirkavrba** [comment]
I also encountered this issue when building a Spring boot application using `openjdk:17-alpine`, when I switched the image to `openjdk:17` it started working again

**Comment by dk2k** [comment]
Try installing fontconfig and restarting the app. Helped me on CentOS 8

**Comment by timmolter** [comment]
Closing as **works as intended / environment issue** rather than an XChart bug.

### Root cause

The `NullPointerException` comes entirely from inside the JDK's AWT font subsystem, not from XChart:

```
java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
    at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
    at sun.awt.FontConfiguration.readFontConfigFile(...)
    at sun.awt.X11FontManager.createFontConfiguration(...)
    at java.awt.font.TextLayout.<init>(...)
    at org.knowm.xchart...ChartTitle.getBoundsHint(...)
```

`FontConfiguration.head` is `null` because the runtime has **no `fontconfig` native library and/or no installed fonts**. Any AWT text rendering (measuring/drawing the chart title, axis labels, etc.) needs the font stack, so XChart can't produce an image without it. This most commonly shows up on **Alpine / musl / "slim" JRE base images** that ship a JDK without fonts. It surfaced going from Java 16 → 17 because the X11 font manager now throws an NPE on a missing font config instead of degrading silently.

This is confirmed by the reports in this thread: `openjdk:17-alpine` fails while plain `openjdk:17` works, and installing `fontconfig` fixes it. It's a well-known issue that affects every AWT-based library (JFreeChart, Apache POI, etc.), not just XChart.

### The fix

Install fonts + fontconfig in your runtime environment.

**Alpine Docker:**
```dockerfile
RUN apk add --no-cache fontconfig ttf-dejavu
```

**Debian/Ubuntu slim:**
```dockerfile
RUN apt-get update && apt-get install -y fontconfig fonts-dejavu && rm -rf /var/lib/apt/lists/*
```

**Alternatively**, avoid the package install by using a runtime that already ships fonts:
- A non-Alpine / non-slim base image (e.g. `eclipse-temurin:17-jre` on Debian) — this is why `openjdk:17` works where `openjdk:17-alpine` fails.
- A JDK distribution that bundles fonts, e.g. **BellSoft Liberica "Full"** (which also offers musl/Alpine builds).

This is a well-documented issue across the JVM ecosystem — searching for `sun.awt.FontConfiguration.head is null` turns up the same fix (install `fontconfig` + fonts) for JFreeChart, Apache POI, and any other AWT-based library on minimal Linux images.

Since there's nothing XChart can do to substitute for a missing native font stack, closing this out. Please re-open if you hit the NPE **after** installing fontconfig + fonts.
