### ISSUE TITLE
NPE related to tooltip handling

### ISSUE THREAD

**Issue by sjaenick** [knowm/XChart#740]
xchart 3.8.3; plot with `.setToolTipsEnabled(true);`:
```
java.lang.NullPointerException: Cannot invoke "org.knowm.xchart.internal.chartpart.ToolTips.clearData()" because "this.toolTips" is null
	at org.knowm.xchart.internal.chartpart.PlotContent_.paint(PlotContent_.java:61)
	at org.knowm.xchart.internal.chartpart.Plot_.paint(Plot_.java:40)
	at org.knowm.xchart.internal.chartpart.Plot_Circular.paint(Plot_Circular.java:56)
	at org.knowm.xchart.PieChart.paint(PieChart.java:128)
	at org.knowm.xchart.XChartPanel.paintComponent(XChartPanel.java:168)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
```

**Comment by sjaenick** [comment]
Some more information here:

```
chart.getStyler().setToolTipsEnabled(true);
chart.addSeries(...));
```

works, while this one triggers the NPE:

```
chart.addSeries(...));
chart.getStyler().setToolTipsEnabled(true);
```
